version: '{build}'
image: Visual Studio 2022

# Używamy własnych kroków build
build: off

# Zmienna z konfiguracją
environment:
  CONFIG: RelWithDebInfo

init:
  - cmd: |
      echo Build worker: %APPVEYOR_BUILD_WORKER_IMAGE%
      ver

install:
  - cmd: |
      git submodule update --init --recursive
      call setup.bat

before_build:
  - cmd: |
      if not exist build mkdir build
      # cd build
      cmake .. -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=%CONFIG%

build_script:
  - cmd: |
      cmake --build . --config %CONFIG% --parallel
      cd ..

after_build:
  - cmd: |
      echo Copying shaders...
      if not exist build\bin\%CONFIG%\shaders mkdir build\bin\%CONFIG%\shaders
      xcopy /E /Y shaders build\bin\%CONFIG%\shaders\

artifacts:
  - path: build\bin\%CONFIG%\*.exe
    name: binaries
  - path: build\pdb\%CONFIG%\*.pdb
    name: symbols
  - path: build\bin\%CONFIG%\shaders
    name: shaders
