sonar.organization=maszyna-eu07
sonar.projectKey=MaSzyna-EU07_maszyna
sonar.projectName=maszyna

sonar.sources=.
sonar.sourceEncoding=UTF-8

# Exclusions
sonar.exclusions=betterRenderer/**,ref/**,imgui/**,stb/**,build/**,bw-output/**
